# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json

language: "en-US"
early_access: false
chat:
  auto_reply: true
reviews:
  profile: "assertive"
  poem: false
  request_changes_workflow: true
  high_level_summary: true
  review_status: true
  collapse_walkthrough: false
  auto_review:
    enabled: true
    drafts: false
    base_branches:
      - develop
      - develop-postgres
      - main
  path_filters:
    - '!**/docs/docs/**'
    - "!*.html"
    - "!*.md"
    - "!*.svg" 

# Add test generation configuration
test_generation:
  enabled: true
  frameworks:
    - jest  # For React-based components (Talawa-Admin)
    - mocha # If used in any parts of the codebase
  file_patterns:
    component: "**/*.{jsx,tsx,js,ts}"
    test: "{__tests__,tests}/**/*.test.{js,ts,jsx,tsx}"
  coverage_targets:
    - "src/"
    - "lib/"
    - "components/"
  exclude:
    - "node_modules/"
    - "dist/"
    - "build/"
  options:
    prioritize_uncovered: true
    mock_dependencies: true
    generate_snapshots: false
    test_naming_convention: "describe_it"